- name: "Check for groups existence"
  shell: getent group {{ ssh_group }}
  register: group
  when: ssh_group is defined
  ignore_errors: true

- name: "Check if AllowGroups config exists in sshd_config"
  shell: cat {{ sshd_config }} | grep AllowGroups
  register: allowgroups
  ignore_errors: true
  when:
    - ssh_group is defined
    - group.rc == 0

- name: "Add group to AllowGroups in SSH configuration, if group found"
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    insertafter: "EOF"
    line: 'AllowGroups {{ ssh_group }}'
    state: present
    validate: 'sshd -T -f %s'
    mode: 0600
  notify: "Restart SSH Daemon"
  when:
    - ssh_group is defined
    - group.rc == 0
    - allowgroups.rc != 0

- name: "Append group to AllowGroups in SSH configuration, if group found"
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    regexp: "^AllowGroups"
    line: '{{ allowgroups.stdout }} {{ ssh_group }}'
    state: present
    validate: 'sshd -T -f %s'
    mode: 0600
  notify: "Restart SSH Daemon"
  when:
    - ssh_group is defined
    - group.rc == 0
    - allowgroups.rc == 0
    - ssh_group|string not in allowgroups.stdout